# Generated by Django 3.2.5 on 2021-12-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=10)),
                ('password2', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=70)),
            ],
        ),
    ]
